mariadb_root_password: "{{ vault_mariadb_root_password }}"
redis_socket: /var/run/redis/redis-server.sock

php_memory_limit: 512M
php_upload_max_filesize: 16G
php_post_max_size: 16G
php_max_execution_time: 360
php_opcache_interned_strings_buffer: 16
nextcloud_serverid: 1