# group_vars/pfsense/firewall/VLAN40_SERVERS/blocking.yml
# Règles de BLOCAGE du VLAN serveurs (VLAN40_SERVERS).
fw_vlan40_servers_block:

  - name: BLOCK_VLAN40_to_VLAN10
    interface: VLAN40_SERVERS
    action: block
    protocol: any
    source: VLAN40_SERVERS_NET
    destination: VLAN10_ADMIN_NET
    description: Bloquer serveurs vers admin

  - name: BLOCK_ALL_to_pfSense_SERVERS
    interface: VLAN40_SERVERS
    action: block
    protocol: any
    source: VLAN40_SERVERS_NET
    destination: "(self)"
    description: Bloquer accès pfSense depuis VLAN40
