# group_vars/pfsense/firewall/VLAN40_SERVERS/blocking.yml
# Regles de BLOCAGE du VLAN serveurs (VLAN40_SERVERS).
fw_vlan40_servers_block:

  - name: BLOCK_VLAN40_to_pfSense
    interface: VLAN40_SERVERS
    action: block
    protocol: any
    source: VLAN40_SERVERS_NET
    destination: (self)
    description: Bloquer acces pfSense depuis VLAN40 hors exceptions explicites

  - name: BLOCK_VLAN40_to_INTERNAL_NETWORKS
    interface: VLAN40_SERVERS
    action: block
    protocol: any
    source: VLAN40_SERVERS_NET
    destination: INTERNAL_NETWORKS
    description: Bloquer inter-VLAN serveurs hors exceptions explicites
