---
- name: Déployer Zabbix Server
  hosts: zabbix
  become: true
  gather_facts: true
  roles:
    - base_server
    - zabbix_server
    - zabbix_https

- name: Déployer Zabbix Agent 2 sur les serveurs Linux
  hosts: nextcloud:glpi:proxmox:qdevice:pbs:wazuh
  become: true
  tags: 
    - zabbix_agent2
  gather_facts: true
  roles:
    - zabbix_agent2

- name: Déployer Zabbix Agent 2 sur les contrôleurs de domaine
  hosts: windows
  gather_facts: false
  tags:
    - zabbix_agent2_windows
  roles:
    - zabbix_agent2_windows

- name: Enregistrer les serveurs applicatifs dans Zabbix
  hosts: zabbix
  become: false
  gather_facts: false
  tags:
    - zabbix_api
  roles:
    - zabbix_api_hosts
    - role: zabbix_api_mail
      tags:
        - zabbix_mail
    - role: zabbix_api_ldaps
      tags:
        - zabbix_ldaps
    - role: zabbix_api_dashboard
      tags:
        - zabbix_dashboard
    - role: zabbix_api_maps
      tags:
        - zabbix_maps
    - role: zabbix_snmp_test
      tags:
        - zabbix_snmp_test
