# group_vars/pfsense/firewall/VLAN20_USERS/blocking.yml
# Règles de BLOCAGE du VLAN utilisateurs (VLAN20_USERS).
fw_vlan20_users_block:

  - name: BLOCK_VLAN20_to_VLAN10
    interface: VLAN20_USERS
    action: block
    protocol: any
    source: VLAN20_USERS_NET
    destination: VLAN10_ADMIN_NET
    description: Bloquer utilisateurs vers admin

  - name: BLOCK_VLAN20_to_VLAN40
    interface: VLAN20_USERS
    action: block
    protocol: any
    source: VLAN20_USERS_NET
    destination: VLAN40_SERVERS_NET
    description: Bloquer utilisateurs vers serveurs (hors règles autorisées)

  - name: BLOCK_ALL_to_pfSense
    interface: VLAN20_USERS
    action: block
    protocol: any
    source: VLAN20_USERS_NET
    destination: "(self)"
    description: Bloquer accès pfSense depuis VLAN20
