# group_vars/pfsense/firewall/VLAN20_USERS/blocking.yml
# Regles de BLOCAGE du VLAN utilisateurs (VLAN20_USERS).
fw_vlan20_users_block:

  - name: BLOCK_VLAN20_to_pfSense
    interface: VLAN20_USERS
    action: block
    protocol: any
    source: VLAN20_USERS_NET
    destination: (self)
    description: Bloquer acces pfSense depuis VLAN20

  - name: BLOCK_VLAN20_to_INTERNAL_NETWORKS
    interface: VLAN20_USERS
    action: block
    protocol: any
    source: VLAN20_USERS_NET
    destination: INTERNAL_NETWORKS
    description: Bloquer inter-VLAN utilisateurs hors exceptions explicites
